---
to: ./tests/<%= name %>.test.js
---

// Generated by halva-cli
// A simple test to check global scope
//
describe('Halva test', () => {
  describe('test global', () => {
    it('Get global var', async () => {
        console.log(halva_accounts[0].address);
    });
  });
});
